global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'legal-workbench-services'
    static_configs:
      - targets:
        - 'api-stj:8000'
        - 'api-text-extractor:8001'
        - 'api-doc-assembler:8002'
        - 'api-ledes-converter:8003'
        - 'api-trello:8004'
        - 'api-ccui-ws:8005'
    metrics_path: /metrics

  - job_name: 'traefik'
    static_configs:
      - targets: ['reverse-proxy:8080']
